name: Persistent Terminal Website

on:
  workflow_dispatch:
  schedule:
    # Restart the workflow every 6 hours to prevent timeout
    - cron: '0 */6 * * *'

jobs:
  deploy-terminal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker container with terminal
      run: |
        # Start a container with a persistent terminal environment
        docker run -d \
          --name=persistent-terminal \
          -v terminal-data:/data \
          -e PERSISTENT_HOME=1 \
          -p 7681:7681 \
          linuxserver/webtop:ubuntu-xfce
        
        # Install basic tools
        docker exec persistent-terminal apt-get update
        docker exec persistent-terminal apt-get install -y \
          git curl wget nano tmux htop

    - name: Setup ngrok
      uses: https://github.com/gautamkrishnar/setup-ngrok@master
      with:
        ngrok-authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok-region: us # Change to your preferred region

    - name: Expose terminal via ngrok
      run: |
        # Create ngrok tunnel to the terminal service
        ngrok http 7681 --log=stdout > ngrok.log &
        sleep 5
        
        # Extract public URL
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Terminal available at: $NGROK_URL"
        
        # Save URL to GitHub environment
        echo "TERMINAL_URL=$NGROK_URL" >> $GITHUB_ENV
        
        # Keep the workflow running
        tail -f /dev/null

    - name: Post terminal URL
      run: |
        echo "Your persistent terminal is now available at: ${{ env.TERMINAL_URL }}"
        echo "Bookmark this URL - it will remain active as long as this workflow runs"
