name: Persistent Terminal Website

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  deploy-terminal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker container
      run: |
        docker run -d \
          --name=persistent-terminal \
          -v terminal-data:/data \
          -p 7681:7681 \
          linuxserver/webtop:ubuntu-xfce
        
        docker exec persistent-terminal apt-get update
        docker exec persistent-terminal apt-get install -y \
          git curl wget nano tmux htop

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok tunnel
      run: |
        ngrok http 7681 --log=stdout > ngrok.log &
        sleep 5
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Terminal URL: $NGROK_URL"
        echo "TERMINAL_URL=$NGROK_URL" >> $GITHUB_ENV
        tail -f /dev/null
